type Query {
  """
  Returns a boolean ascertaining the address or coordinate provided is within our reach.

  @example
  ```
  geoLocator(address: "123 Main St, New York, NY 10001", coordinate: { lat: 40.7128, lng: -74.0060})
  ```
  """
  geoLocator(address: String, coordinate: Coordinate): Boolean
}